apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  parallelism: 1
  template:
    spec:
      completions: 10
      containers:
      - name: hello-container
        image: busybox
        command: ["echo", "Hello I am from job"]
      restartPolicy: Never
