apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-06-12T19:01:01Z"
    generateName: webapp-6684ccd7b8-
    labels:
      app: webapp
      pod-template-hash: 6684ccd7b8
    name: webapp-6684ccd7b8-9wspj
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-6684ccd7b8
      uid: efd8a4e0-85df-4b5d-b7d0-1c3d92b44a9a
    resourceVersion: "18535"
    uid: 491882f7-9ebc-47e0-9f1f-fe108e5b29c9
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xdbht
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-xdbht
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:08Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:08Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://0911693b704179c52aadc9a3542728a564e071dbff4edbaa7329713842fcce7b
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-06-12T19:01:08Z"
    hostIP: 192.168.65.4
    phase: Running
    podIP: 10.1.0.46
    podIPs:
    - ip: 10.1.0.46
    qosClass: BestEffort
    startTime: "2023-06-12T19:01:01Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-06-12T19:01:01Z"
    generateName: webapp-6684ccd7b8-
    labels:
      app: webapp
      pod-template-hash: 6684ccd7b8
    name: webapp-6684ccd7b8-f8mc8
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-6684ccd7b8
      uid: efd8a4e0-85df-4b5d-b7d0-1c3d92b44a9a
    resourceVersion: "18552"
    uid: 21ef85c3-cadd-411f-ab68-98f8acea577a
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rjdwj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-rjdwj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:12Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:12Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://75973e9eae07c0eae6bc150a8fb7b3c344488e81435177479dad0f638006b0a4
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-06-12T19:01:12Z"
    hostIP: 192.168.65.4
    phase: Running
    podIP: 10.1.0.48
    podIPs:
    - ip: 10.1.0.48
    qosClass: BestEffort
    startTime: "2023-06-12T19:01:01Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-06-12T19:01:01Z"
    generateName: webapp-6684ccd7b8-
    labels:
      app: webapp
      pod-template-hash: 6684ccd7b8
    name: webapp-6684ccd7b8-p68db
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-6684ccd7b8
      uid: efd8a4e0-85df-4b5d-b7d0-1c3d92b44a9a
    resourceVersion: "18518"
    uid: df4098e3-056d-4063-8e3a-693c402740ec
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-j4v7t
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-j4v7t
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:05Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:05Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://ae6d473210a9744b1333f276e282f9feba3b20cdc0f9677a35777176d095b58f
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-06-12T19:01:04Z"
    hostIP: 192.168.65.4
    phase: Running
    podIP: 10.1.0.44
    podIPs:
    - ip: 10.1.0.44
    qosClass: BestEffort
    startTime: "2023-06-12T19:01:01Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-06-12T19:01:01Z"
    generateName: webapp-6684ccd7b8-
    labels:
      app: webapp
      pod-template-hash: 6684ccd7b8
    name: webapp-6684ccd7b8-qw789
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-6684ccd7b8
      uid: efd8a4e0-85df-4b5d-b7d0-1c3d92b44a9a
    resourceVersion: "18527"
    uid: 6fb4c342-ae8c-42bc-b4fc-6a1b4d704b46
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wl5gg
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-wl5gg
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://a687fa814a7dd9b34de02eeef2888b406b48456da4f1b865f95aa7e9efbd94fa
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-06-12T19:01:06Z"
    hostIP: 192.168.65.4
    phase: Running
    podIP: 10.1.0.45
    podIPs:
    - ip: 10.1.0.45
    qosClass: BestEffort
    startTime: "2023-06-12T19:01:01Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-06-12T19:01:01Z"
    generateName: webapp-6684ccd7b8-
    labels:
      app: webapp
      pod-template-hash: 6684ccd7b8
    name: webapp-6684ccd7b8-rtdkx
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-6684ccd7b8
      uid: efd8a4e0-85df-4b5d-b7d0-1c3d92b44a9a
    resourceVersion: "18544"
    uid: 767b2f0b-aeb8-4ade-86bd-75feec9ae740
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xt7xz
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-xt7xz
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:10Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:10Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-06-12T19:01:01Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://075e64535d920e96bce7f912ff59f50f92465d93ee4a7ed6967872a977ca8eb8
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:af296b188c7b7df99ba960ca614439c99cb7cf252ed7bbc23e90cfda59092305
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-06-12T19:01:10Z"
    hostIP: 192.168.65.4
    phase: Running
    podIP: 10.1.0.47
    podIPs:
    - ip: 10.1.0.47
    qosClass: BestEffort
    startTime: "2023-06-12T19:01:01Z"
kind: List
metadata:
  resourceVersion: ""
