apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: ALPHA
      value: "alpha"
  - name: beta
    image: busybox
    command: ["sleep", "4800"]
    env:
    - name: BETA
      value: "beta"
