apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-yourname
spec:
  containers:
  - image: nginx
    name: use-pv
    volumeMounts:
      - name: data-volume
        mountPath: /data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pv-1
